# Default values for container-build.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/buildah/stable
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

build:
  configMap:
    enabled: false
    create: true
    name: ""
    dockerfileData: |
      # Your Dockerfile data should be placed here.
  url:
    enabled: false
    uri: ""
    authSecret:
      enabled: true
      create: true
      name: ""
      username: ""
      password: ""
  git:
    enabled: false
    uri: ""
    authSecret:
      enabled: true
      create: true
      name: ""
      sshPrivateKey: ""
  source:
    authSecret:
      enabled: false
      create: true
      name: ""
      registry: ""
      username: ""
      password: ""
  destination:
    registry: ""
    repository: ""
    tag: ""
    authSecret:
      enabled: false
      create: true
      name: ""
      username: ""
      password: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podRestartPolicy: Never

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
