{{- if and (.Values.build.configMap.enabled) (.Values.build.configMap.create) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.build.configMap.name | default (include "container-build.fullname" .) }}
  labels:
    {{- include "container-build.labels" . | nindent 4 }}
data:
  Dockerfile: |
    {{- .Values.build.configMap.dockerfileData | nindent 4 }}
{{- end -}}
