---
{{- if or (.Values.build.url.enabled) (.Values.build.git.enabled) }}
{{- /*
Only a single source is supported at a time between `url` and `git` so if one
of the two is enabled, and it isn't the one we test with the ternary then the
data we want must be in the other object.
*/ -}}
{{- $config := ternary .Values.build.url .Values.build.git .Values.build.url.enabled }}
{{- if $config.authSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $config.authSecret.name | default (include "container-build.configAuthSecretName" .) }}
  labels:
    {{- include "container-build.labels" . | nindent 4 }}
{{- if .Values.build.url.enabled }}
kind: kubernetes.io/basic-auth
stringData:
  username: {{ $config.authSecret.username }}
  password: {{ $config.authSecret.password }}
{{- end }}
{{- if .Values.build.git.enabled }}
kind: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    {{- $config.authSecret.sshPrivateKey | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
