{{- if .Values.build.source.authSecret.create }}
---
apiVersion: v1
kind: secret
metadata:
  name: {{ .Values.build.source.authSecret.name | default (include "container-build.sourceAuthSecretName" .) }}
  labels:
    {{- include "container-build.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {{- with .Values.build.source.authSecret }}
    {
      "auths": {
        "https://{{ .registry }}": {
          "username": "{{ .username }}",
          "password": "{{ .password }}",
          "auth": '{{ template "container-build.sourceAuthSecretData" . }}'
        }
      }
    }
    {{- end }}
{{- end }}
{{- if .Values.build.destination.authSecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.build.destination.authSecret.name | default (include "container-build.destinationAuthSecretName" .) }}
  labels:
    {{- include "container-build.labels" . | nindent 4 }}
stringData:
  .dockerconfigjson: |
    {{- with .Values.build.destination }}
    {
      "auths": {
        "https://{{ .registry }}": {
          "username": "{{ .authSecret.username }}",
          "password": "{{ .authSecret.password }}",
          "auth": '{{ include "container-build.destinationAuthSecretData" . }}'
        }
      }
    }
    {{- end }}
{{- end }}
